const APP_VERSION='0.1.0';
const STORAGE_KEY='nestegg-data-v1';
const THEME_KEY='nestegg-theme';
const START_DATE='2026-07-01';
const months=['gennaio','febbraio','marzo','aprile','maggio','giugno','luglio','agosto','settembre','ottobre','novembre','dicembre'];
const todayISO=toISO(new Date());
const expenseTypes={fixed_recurring:'Fissa ricorrente',variable_recurring:'Ricorrente variabile',average_estimate:'Media stimata',one_off:'Una tantum',due_date:'Con scadenza',installment:'Rateizzata',project_extra:'Straordinaria / Progetto'};
const freqs={none:'Nessuna',daily:'Giornaliera',weekly:'Settimanale',monthly:'Mensile',bimonthly:'Bimestrale',quarterly:'Trimestrale',semiannual:'Semestrale',yearly:'Annuale'};
const seedCats=[['casa','Casa'],['mutuo','Mutuo / Affitto'],['condominio','Condominio'],['utenze','Utenze'],['alimentari','Alimentari'],['auto','Auto'],['bambini','Bambini / Scuola'],['salute','Salute'],['tasse','Tasse e imposte'],['assicurazioni','Assicurazioni'],['prestiti','Prestiti / Finanziamenti'],['carte','Carte di credito'],['abbonamenti','Abbonamenti'],['tempo','Tempo libero'],['viaggi','Viaggi'],['regali','Regali'],['contanti','Contanti'],['lavori','Ristrutturazione / Lavori'],['extra','Extra']].map(([id,name])=>({id,name}));
let state={view:'home',month:ym(new Date())<'2026-07'?'2026-07':ym(new Date()),theme:localStorage.getItem(THEME_KEY)||'light',msg:'',menu:false};
let data=loadData();
applyTheme();
render();
Object.assign(window,{go,saveExpense,deleteExpense,markDuePaid,markDuePending,changeMonth,toggleTheme,seedDemo,clearData});
function defaultData(){return{settings:{startDate:START_DATE,notificationEmail:'',webNotifications:true,emailNotifications:true},categories:seedCats,expenses:[],dueDates:[]}}
function loadData(){try{return{...defaultData(),...(JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}'))}}catch{return defaultData()}}
function saveData(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function uid(p='id'){return p+'_'+Math.random().toString(36).slice(2,9)+'_'+Date.now().toString(36)}
function toISO(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function ym(d){return toISO(d).slice(0,7)}
function addDays(iso,n){const d=new Date(iso+'T00:00:00');d.setDate(d.getDate()+n);return toISO(d)}
function addMonths(iso,n){const d=new Date(iso+'-01T00:00:00');d.setMonth(d.getMonth()+n);return toISO(d).slice(0,7)}
function esc(v){return String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]))}
function eur(v){return new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(v||0))}
function dmy(v){if(!v)return'';return new Date(v+'T00:00:00').toLocaleDateString('it-IT',{day:'2-digit',month:'short',year:'numeric'})}
function monthLabel(m=state.month){const [y,mo]=m.split('-').map(Number);return `${months[mo-1]} ${y}`}
function cat(id){return data.categories.find(c=>c.id===id)||{id:'extra',name:'Extra'}}
function isMonth(date,m=state.month){return String(date||'').startsWith(m)}
function overdue(d){return d.status!=='paid'&&d.dueDate<todayISO}
function today(d){return d.status!=='paid'&&d.dueDate===todayISO}
function upcoming(d,n=7){return d.status!=='paid'&&d.dueDate>todayISO&&d.dueDate<=addDays(todayISO,n)}
function msg(t){state.msg=t;render();setTimeout(()=>{if(state.msg===t){state.msg='';render()}},3000)}
function applyTheme(){document.documentElement.setAttribute('data-theme',state.theme);localStorage.setItem(THEME_KEY,state.theme)}
function toggleTheme(){state.theme=state.theme==='dark'?'light':'dark';applyTheme();render()}
function go(v){state.view=v;state.menu=false;render()}
function changeMonth(n){state.month=addMonths(state.month,n);render()}
function shell(content){return `<div class="shell"><aside class="sidebar"><div class="brand"><img src="assets/nest-egg-logo.svg" alt=""><div class="brandText"><b>Nest Egg</b><span>Budget familiare</span></div></div><nav class="nav">${nav()}</nav><div class="sideFoot">${APP_VERSION} · dal 1 luglio 2026</div></aside><main class="main"><div class="topbar"><button onclick="state.menu=!state.menu;render()">☰</button><img src="assets/nest-egg-logo.svg" alt=""><button onclick="toggleTheme()">${state.theme==='dark'?'☀':'☾'}</button></div>${state.menu?`<div class="mobileMenu">${nav()}</div>`:''}<div class="app">${state.msg?`<div class="toast">${esc(state.msg)}</div>`:''}${content}</div><button class="mobileFab" onclick="go('new')">+ Nuova spesa</button></main></div>`}
function nav(){return[['home','⌂','Dashboard'],['new','＋','Nuova spesa'],['expenses','▤','Spese'],['dues','◷','Scadenze'],['budget','▥','Budget'],['settings','•••','Impostazioni']].map(([v,i,l])=>`<button class="${state.view===v?'active':''}" onclick="go('${v}')"><i>${i}</i><b>${l}</b></button>`).join('')}
function render(){const views={home,new:newExpense,expenses:expensesView,dues:duesView,budget:budgetView,settings:settingsView};document.getElementById('app').innerHTML=shell((views[state.view]||home)())}
function hero(title,sub=''){return `<section class="hero"><div><div class="eyebrow">Nest Egg</div><h1>${title}</h1>${sub?`<p class="sub">${sub}</p>`:''}</div><div class="actions"><button class="ghost" onclick="changeMonth(-1)">‹</button><button class="ghost">${monthLabel()}</button><button class="ghost" onclick="changeMonth(1)">›</button></div></section>`}
function home(){const k=kpis();return `${hero('Dashboard familiare','Spese, scadenze e budget sempre sotto controllo.')}<section class="grid cols4"><div class="card metric"><small>Uscite mese</small><strong>${eur(k.month)}</strong><span class="delta">${monthLabel()}</span></div><div class="card metric"><small>Scadenze aperte</small><strong>${k.open}</strong><span class="delta">Da pagare o controllare</span></div><div class="card metric"><small>Prossimi 7 giorni</small><strong>${eur(k.next7)}</strong><span class="delta">Scadenze imminenti</span></div><div class="card metric"><small>Scadute</small><strong>${k.overdue}</strong><span class="delta">Non pagate</span></div></section><section class="section grid cols2"><div class="card"><div class="sectionHead"><h2>Oggi e prossimi giorni</h2><button class="ghost" onclick="go('dues')">Vedi tutto</button></div>${dailyBox()}</div><div class="card"><div class="sectionHead"><h2>Spese per categoria</h2></div>${categoryBox()}</div></section><section class="section card"><div class="sectionHead"><h2>Andamento uscite mensili</h2><span class="muted">${state.month.slice(0,4)}</span></div>${annualChart()}</section>`}
function kpis(){const open=data.dueDates.filter(d=>d.status!=='paid');const next=open.filter(d=>today(d)||upcoming(d));return{month:monthTotal(state.month),open:open.length,next7:next.reduce((s,d)=>s+Number(d.amount||0),0),overdue:open.filter(overdue).length}}
function dueRow(d){const st=d.status==='paid'?'Pagata':overdue(d)?'Scaduta':today(d)?'Oggi':'Da pagare';const cls=d.status==='paid'?'ok':overdue(d)?'danger':today(d)?'warn':'';return `<div class="row"><div><b>${esc(d.title)}</b><span>${esc(cat(d.categoryId).name)} · ${dmy(d.dueDate)} · <span class="pill ${cls}">${st}</span></span></div><div><div class="amount">${eur(d.amount)}</div>${d.status==='paid'?`<button class="linkBtn" onclick="markDuePending('${d.id}')">Ripristina</button>`:`<button class="linkBtn" onclick="markDuePaid('${d.id}')">Pagata</button>`}</div></div>`}
function dailyBox(){const rows=data.dueDates.filter(d=>d.status!=='paid'&&(overdue(d)||today(d)||upcoming(d))).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));return rows.length?`<div class="list">${rows.slice(0,8).map(dueRow).join('')}</div>`:`<div class="empty">Nessuna scadenza urgente.</div>`}
function categoryBox(){const rows=catTotals(state.month).slice(0,7);if(!rows.length)return `<div class="empty">Nessuna spesa nel mese.</div>`;const max=Math.max(...rows.map(r=>r.amount),1);return `<div class="list">${rows.map(r=>`<div><div class="sectionHead"><b>${esc(r.name)}</b><span>${eur(r.amount)}</span></div><div class="bar" style="height:12px;background:var(--soft)"><span style="display:block;height:12px;border-radius:12px;background:var(--brand);width:${Math.max(5,r.amount/max*100)}%"></span></div></div>`).join('')}</div>`}
function annualChart(){const y=Number(state.month.slice(0,4));const vals=Array.from({length:12},(_,i)=>monthTotal(`${y}-${String(i+1).padStart(2,'0')}`));const max=Math.max(...vals,1);return `<div class="chartBox">${vals.map((v,i)=>`<div class="bar" style="height:${Math.max(4,v/max*200)}px"><span>${months[i].slice(0,3)}</span></div>`).join('')}</div>`}
function monthTotal(m){return data.expenses.filter(e=>isMonth(e.date,m)).reduce((s,e)=>s+Number(e.amount||0),0)+data.dueDates.filter(d=>isMonth(d.dueDate,m)).reduce((s,d)=>s+Number(d.amount||0),0)}
function catTotals(m){const map={};const add=(id,a)=>{const c=cat(id);map[id]??={name:c.name,amount:0};map[id].amount+=Number(a||0)};data.expenses.filter(e=>isMonth(e.date,m)).forEach(e=>add(e.categoryId,e.amount));data.dueDates.filter(d=>isMonth(d.dueDate,m)).forEach(d=>add(d.categoryId,d.amount));return Object.values(map).sort((a,b)=>b.amount-a.amount)}
function newExpense(){return `${hero('Nuova spesa','Inserisci una spesa familiare reale, stimata, ricorrente o con scadenza.')}<div class="card"><form class="form" onsubmit="saveExpense(event)"><div class="formGrid"><div class="field"><label>Tipologia</label><select name="expenseType">${Object.entries(expenseTypes).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div><div class="field"><label>Categoria</label><select name="categoryId">${data.categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field full"><label>Descrizione</label><input name="title" placeholder="Mutuo casa, TARI, spesa supermercato" required></div><div class="field"><label>Importo</label><input name="amount" type="number" step="0.01" min="0" required></div><div class="field"><label>Data riferimento</label><input name="date" type="date" value="${todayISO<START_DATE?START_DATE:todayISO}" required></div><div class="field"><label>Frequenza</label><select name="frequency">${Object.entries(freqs).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div><div class="field"><label>Data scadenza</label><input name="dueDate" type="date"></div><div class="field"><label>Metodo pagamento</label><input name="paymentMethod" placeholder="conto, carta, contanti"></div><div class="field full"><label>Note</label><textarea name="notes"></textarea></div></div><div class="actions"><button class="primary">Salva spesa</button><button type="button" class="ghost" onclick="go('home')">Annulla</button></div></form></div>`}
function saveExpense(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const exp={id:uid('exp'),title:f.title,amount:Number(f.amount||0),date:f.date,categoryId:f.categoryId,expenseType:f.expenseType,frequency:f.frequency,paymentMethod:f.paymentMethod||'',notes:f.notes||'',createdAt:new Date().toISOString()};data.expenses.unshift(exp);if(f.dueDate||['fixed_recurring','due_date','installment','project_extra'].includes(f.expenseType)){data.dueDates.unshift({id:uid('due'),title:f.title,amount:Number(f.amount||0),dueDate:f.dueDate||f.date,categoryId:f.categoryId,status:'pending',sourceExpenseId:exp.id,createdAt:new Date().toISOString()})}saveData();state.view='home';msg('Spesa salvata.')}
function expensesView(){const rows=data.expenses.filter(e=>isMonth(e.date)).sort((a,b)=>b.date.localeCompare(a.date));return `${hero('Spese','Movimenti inseriti nel mese selezionato.')}<div class="card">${rows.length?`<table class="table"><thead><tr><th>Data</th><th>Descrizione</th><th>Tipologia</th><th>Importo</th></tr></thead><tbody>${rows.map(e=>`<tr><td>${dmy(e.date)}</td><td><b>${esc(e.title)}</b><br><span>${esc(cat(e.categoryId).name)}</span></td><td>${expenseTypes[e.expenseType]}</td><td>${eur(e.amount)}<br><button class="linkBtn dangerText" onclick="deleteExpense('${e.id}')">Elimina</button></td></tr>`).join('')}</tbody></table>`:`<div class="empty">Nessuna spesa inserita.</div>`}</div>`}
function duesView(){const rows=[...data.dueDates].sort((a,b)=>a.dueDate.localeCompare(b.dueDate));return `${hero('Scadenze','Promemoria dentro l’app, con predisposizione email.')}<div class="card">${rows.length?`<div class="list">${rows.map(dueRow).join('')}</div>`:`<div class="empty">Nessuna scadenza inserita.</div>`}</div>`}
function budgetView(){const rows=catTotals(state.month);return `${hero('Budget annuale','Prima vista base: uscite per mese e categoria.')}<section class="grid cols2"><div class="card"><h2>${monthLabel()}</h2>${rows.length?`<div class="list">${rows.map(r=>`<div class="row"><b>${esc(r.name)}</b><div class="amount">${eur(r.amount)}</div></div>`).join('')}</div>`:`<div class="empty">Nessun dato per il mese.</div>`}</div><div class="card"><h2>Grafico annuale</h2>${annualChart()}</div></section>`}
function settingsView(){return `${hero('Impostazioni','Configurazione base MVP.')}<div class="card"><div class="form"><div class="field"><label>Data avvio operativo</label><input readonly value="1 luglio 2026"></div><div class="field"><label>Notifiche</label><input readonly value="Web app + email nella prossima fase database"></div><div class="actions"><button class="primary" onclick="seedDemo()">Carica dati demo</button><button class="ghost" onclick="toggleTheme()">Cambia tema</button><button class="ghost dangerText" onclick="clearData()">Cancella dati locali</button></div></div></div>`}
function markDuePaid(id){const d=data.dueDates.find(x=>x.id===id);if(d){d.status='paid';d.paidDate=todayISO;saveData();render()}}
function markDuePending(id){const d=data.dueDates.find(x=>x.id===id);if(d){d.status='pending';delete d.paidDate;saveData();render()}}
function deleteExpense(id){data.expenses=data.expenses.filter(e=>e.id!==id);data.dueDates=data.dueDates.filter(d=>d.sourceExpenseId!==id);saveData();render()}
function seedDemo(){data=defaultData();data.expenses=[{id:uid('exp'),title:'Spesa supermercato media',amount:180,date:'2026-07-06',categoryId:'alimentari',expenseType:'average_estimate',frequency:'weekly'},{id:uid('exp'),title:'Carburante',amount:90,date:'2026-07-08',categoryId:'auto',expenseType:'variable_recurring',frequency:'weekly'}];data.dueDates=[{id:uid('due'),title:'Mutuo casa',amount:850,dueDate:'2026-07-05',categoryId:'mutuo',status:'pending'},{id:uid('due'),title:'Assicurazione auto',amount:620,dueDate:'2026-07-15',categoryId:'assicurazioni',status:'pending'},{id:uid('due'),title:'TARI',amount:450,dueDate:'2026-11-30',categoryId:'tasse',status:'pending'}];saveData();state.view='home';msg('Dati demo caricati.')}
function clearData(){if(confirm('Cancellare i dati locali di Nest Egg?')){localStorage.removeItem(STORAGE_KEY);data=defaultData();render()}}
