const APP_VERSION='0.1.0';
const STORAGE_KEY='nestegg-data-v1';
const THEME_KEY='nestegg-theme';
const START_DATE='2026-07-01';
const months=['gennaio','febbraio','marzo','aprile','maggio','giugno','luglio','agosto','settembre','ottobre','novembre','dicembre'];
const todayISO=toISO(new Date());
const expenseTypes={fixed_recurring:'Fissa ricorrente',variable_recurring:'Ricorrente variabile',average_estimate:'Media stimata',one_off:'Una tantum',due_date:'Con scadenza',installment:'Rateizzata',project_extra:'Straordinaria / Progetto'};
const freqs={none:'Nessuna',daily:'Giornaliera',weekly:'Settimanale',monthly:'Mensile',bimonthly:'Bimestrale',quarterly:'Trimestrale',semiannual:'Semestrale',yearly:'Annuale'};
const seedCats=[['casa','Casa'],['mutuo','Mutuo / Affitto'],['condominio','Condominio'],['utenze','Utenze'],['alimentari','Alimentari'],['auto','Auto'],['bambini','Bambini / Scuola'],['salute','Salute'],['tasse','Tasse e imposte'],['assicurazioni','Assicurazioni'],['prestiti','Prestiti / Finanziamenti'],['carte','Carte di credito'],['abbonamenti','Abbonamenti'],['tempo','Tempo libero'],['viaggi','Viaggi'],['regali','Regali'],['contanti','Contanti'],['lavori','Ristrutturazione / Lavori'],['extra','Extra']].map(([id,name])=>({id,name}));
let state={view:'home',month:ym(new Date())<'2026-07'?'2026-07':ym(new Date()),theme:localStorage.getItem(THEME_KEY)||'light',message:'',menuOpen:false};
let data=loadData();
applyTheme(); render();
Object.assign(window,{go,saveExpense,deleteExpense,markDuePaid,markDuePending,changeMonth,toggleTheme,seedDemo,clearData,toggleMainMenu});
function defaultData(){return{settings:{startDate:START_DATE,webNotifications:true,emailNotifications:true},categories:seedCats,expenses:[],dueDates:[]}}
function loadData(){try{return{...defaultData(),...(JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}'))}}catch{return defaultData()}}
function saveData(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function uid(p='id'){return p+'_'+Math.random().toString(36).slice(2,9)+'_'+Date.now().toString(36)}
function toISO(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function ym(d){return toISO(d).slice(0,7)}
function addDays(iso,n){const d=new Date(iso+'T00:00:00');d.setDate(d.getDate()+n);return toISO(d)}
function addMonths(iso,n){const d=new Date(iso+'-01T00:00:00');d.setMonth(d.getMonth()+n);return toISO(d).slice(0,7)}
function esc(v){return String(v??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function eur(v){return new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(v||0))}
function dmy(v){if(!v)return'';return new Date(v+'T00:00:00').toLocaleDateString('it-IT',{day:'2-digit',month:'short'})}
function dmyLong(v){if(!v)return'';return new Date(v+'T00:00:00').toLocaleDateString('it-IT',{day:'2-digit',month:'short',year:'numeric'})}
function monthLabel(m=state.month){const [y,mo]=m.split('-').map(Number);return `${months[mo-1]} ${y}`}
function logoIcon(){return 'assets/nest-egg-logo.svg'}
function logoWordmark(){return 'assets/nest-egg-wordmark.svg'}
function cat(id){return data.categories.find(c=>c.id===id)||{id:'extra',name:'Extra'}}
function isMonth(date,m=state.month){return String(date||'').startsWith(m)}
function overdue(d){return d.status!=='paid'&&d.dueDate<todayISO}
function today(d){return d.status!=='paid'&&d.dueDate===todayISO}
function upcoming(d,n=7){return d.status!=='paid'&&d.dueDate>todayISO&&d.dueDate<=addDays(todayISO,n)}
function setMsg(t){state.message=t;render();setTimeout(()=>{if(state.message===t){state.message='';render()}},3200)}
function applyTheme(){document.documentElement.setAttribute('data-theme',state.theme);localStorage.setItem(THEME_KEY,state.theme)}
function toggleTheme(){state.theme=state.theme==='dark'?'light':'dark';applyTheme();render()}
function go(v){state.view=v;state.menuOpen=false;render()}
function changeMonth(n){state.month=addMonths(state.month,n);render()}
function toggleMainMenu(){state.menuOpen=!state.menuOpen;render()}
const NAV_ITEMS=[['home','⌂','Dashboard'],['new','＋','Nuova spesa'],['expenses','▤','Spese'],['dues','◷','Scadenze'],['budget','▥','Budget'],['settings','•••','Impostazioni']];
function navButtons(tag='b'){return NAV_ITEMS.map(([v,ic,l])=>`<button class="${state.view===v?'active':''}" onclick="go('${v}')"><span>${ic}</span><${tag}>${l}</${tag}></button>`).join('')}
function menuDropdown(){if(!state.menuOpen)return'';return `<div class="topMenu" role="menu"><button class="topMenuClose" onclick="toggleMainMenu()" aria-label="Chiudi menu">✕</button><img class="topMenuLogo" src="${logoWordmark()}" alt="Nest Egg">${navButtons('b')}</div>`}
function appShell(content){return `<div class="shell"><aside class="sidebar"><div class="sidebarBrand"><img class="sidebarLogo" src="${logoWordmark()}" alt="Nest Egg" onclick="go('home')" role="button" title="Torna alla Home"></div><nav class="sidebarNav">${navButtons('b')}</nav><div class="sidebarFoot"><div class="version">${APP_VERSION} · Budget Edition · © ${new Date().getFullYear()} johnbruk</div></div></aside><div class="shellMain"><div class="topbar"><div class="headerMenuWrap"><button class="headerIcon" onclick="toggleMainMenu()" title="Apri menu" aria-label="Apri menu">☰</button>${menuDropdown()}</div><img class="topbarLogo" src="${logoIcon()}" alt="Nest Egg" onclick="go('home')" role="button" title="Torna alla Home"><button class="headerIcon" onclick="go('settings')" title="Impostazioni">⚙</button></div><div class="app">${state.message?`<div class="toast">${esc(state.message)}</div>`:''}${content}<div class="version mobileVersion">${APP_VERSION} · Budget Edition · © ${new Date().getFullYear()} johnbruk</div></div></div></div>`}
function monthSelector(){return `<div class="month"><button onclick="changeMonth(-1)">‹</button><strong>${monthLabel()}</strong><button onclick="changeMonth(1)">›</button></div>`}
function render(){const views={home,new:newExpense,expenses:expensesView,dues:duesView,budget:budgetView,settings:settingsView};document.getElementById('app').innerHTML=appShell((views[state.view]||home)())}
function home(){const k=kpis();return `<div class="homeTop"><h1>Dashboard</h1>${monthSelector()}<button class="primary cta" onclick="go('new')">＋ Nuova spesa</button><div class="card heroCard"><div class="kpiGrid three"><div><span>Uscite mese</span><strong>${eur(k.month)}</strong><small>${monthLabel()}</small></div><div><span>Scadenze aperte</span><strong>${k.open}</strong><small>Da pagare</small></div><div><span>Prossimi 7 giorni</span><strong>${eur(k.next7)}</strong><small>Impegni vicini</small></div></div><div class="chartWrap"><div class="chartTitle"><span>Andamento uscite mensili</span><span>${state.month.slice(0,4)}</span></div>${annualChartSvg()}</div></div><div class="grid"><div class="wide">${scadenzeCard()}</div><div>${categoriaCard()}</div><div>${riepilogoCard()}</div></div></div>`}
function kpis(){const open=data.dueDates.filter(d=>d.status!=='paid');const next=open.filter(d=>today(d)||upcoming(d));return{month:monthTotal(state.month),open:open.length,next7:next.reduce((s,d)=>s+Number(d.amount||0),0),overdue:open.filter(overdue).length}}
function annualChartSvg(){const y=Number(state.month.slice(0,4));const vals=Array.from({length:12},(_,i)=>monthTotal(`${y}-${String(i+1).padStart(2,'0')}`));const now=new Date();const actualEnd=y<now.getFullYear()?11:(y===now.getFullYear()?now.getMonth():-1);const visible=vals.map((v,i)=>i<=actualEnd||y===2026?v:0);const max=Math.max(...visible,1);const pts=visible.map((v,i)=>`${(i/11)*100},${52-(v/max)*46}`).join(' ');return `<div class="annualChartBox"><svg class="lineChart" viewBox="0 0 100 58" preserveAspectRatio="none"><line x1="0" y1="52" x2="100" y2="52"></line><line x1="0" y1="30" x2="100" y2="30"></line><polyline points="${pts}"></polyline></svg><div class="chartMonths">${months.map((m,i)=>`<span class="${i>actualEnd&&y>=new Date().getFullYear()?'future':''}">${m.slice(0,3)}</span>`).join('')}</div></div>`}
function scadenzeCard(){const rows=data.dueDates.filter(d=>d.status!=='paid'&&(overdue(d)||today(d)||upcoming(d))).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));return `<div class="card cardLink" onclick="go('dues')" role="button"><b>Scadenze di oggi e prossimi giorni <span class="cardLinkArrow">›</span></b>${rows.length?`<div class="list">${rows.slice(0,5).map(dueRow).join('')}</div>`:`<div class="empty">Nessuna scadenza urgente.</div>`}</div>`}
function categoriaCard(){const rows=catTotals(state.month).slice(0,4);return `<div class="card"><b>Spese per categoria</b>${rows.length?`<div class="statRow">${rows.slice(0,4).map((r,i)=>`<div class="stat ${['tint-blue','tint-orange','tint-sage','tint-pink'][i%4]}"><div class="statHead"><span class="statDot"></span><span class="statLbl">${esc(r.name)}</span></div><strong>${eur(r.amount)}</strong></div>`).join('')}</div>`:`<div class="empty">Nessuna spesa nel mese.</div>`}</div>`}
function riepilogoCard(){const k=kpis();return `<div class="card"><b>Riepilogo scadenze</b><div class="statRow"><div class="stat tint-orange"><div class="statHead"><span class="statDot"></span><span class="statLbl">Scadute</span></div><strong>${k.overdue}</strong><small>Non pagate</small></div><div class="stat tint-sage"><div class="statHead"><span class="statDot"></span><span class="statLbl">Da controllare</span></div><strong>${k.open}</strong><small>Aperte</small></div></div></div>`}
function dueRow(d){const st=d.status==='paid'?'Pagata':overdue(d)?'Scaduta':today(d)?'Oggi':'Da pagare';const tag=d.status==='paid'?'green':overdue(d)?'orange':today(d)?'blue':'gray';return `<div class="row"><div class="date">${dmy(d.dueDate)}</div><div><div class="title">${esc(d.title)}</div><div class="desc">${esc(cat(d.categoryId).name)} · <span class="tag ${tag}">${st}</span></div></div><div class="value">${eur(d.amount)}</div></div>`}
function newExpense(){return `<h1>Nuova spesa</h1>${monthSelector()}<div class="card"><form class="form" onsubmit="saveExpense(event)"><div class="field"><label>Tipologia spesa</label><select name="expenseType">${Object.entries(expenseTypes).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div><div class="field"><label>Categoria</label><select name="categoryId">${data.categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Descrizione</label><input name="title" placeholder="Mutuo casa, TARI, spesa supermercato" required></div><div class="field"><label>Importo</label><input name="amount" type="number" step="0.01" min="0" required></div><div class="field"><label>Data riferimento</label><input name="date" type="date" value="${todayISO<START_DATE?START_DATE:todayISO}" required></div><div class="field"><label>Frequenza</label><select name="frequency">${Object.entries(freqs).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div><div class="field"><label>Data scadenza</label><input name="dueDate" type="date"></div><div class="field"><label>Metodo pagamento</label><input name="paymentMethod" placeholder="Conto, carta, contanti"></div><div class="field"><label>Note</label><textarea name="notes"></textarea></div><div class="actions"><button class="primary">Salva spesa</button><button type="button" class="secondary" onclick="go('home')">Annulla</button></div></form></div>`}
function saveExpense(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const exp={id:uid('exp'),title:f.title,amount:Number(f.amount||0),date:f.date,categoryId:f.categoryId,expenseType:f.expenseType,frequency:f.frequency,paymentMethod:f.paymentMethod||'',notes:f.notes||'',createdAt:new Date().toISOString()};data.expenses.unshift(exp);if(f.dueDate||['fixed_recurring','due_date','installment','project_extra'].includes(f.expenseType)){data.dueDates.unshift({id:uid('due'),title:f.title,amount:Number(f.amount||0),dueDate:f.dueDate||f.date,categoryId:f.categoryId,status:'pending',sourceExpenseId:exp.id,createdAt:new Date().toISOString()})}saveData();state.view='home';setMsg('Spesa salvata.')}
function expensesView(){const rows=data.expenses.filter(e=>isMonth(e.date)).sort((a,b)=>b.date.localeCompare(a.date));return `<h1>Spese</h1>${monthSelector()}${rows.length?`<div class="list">${rows.map(e=>`<div class="row"><div class="date">${dmy(e.date)}</div><div><div class="title">${esc(e.title)}</div><div class="desc">${esc(cat(e.categoryId).name)} · ${expenseTypes[e.expenseType]}</div></div><div class="value">${eur(e.amount)}<br><button class="secondary danger" style="padding:6px;margin-top:6px" onclick="deleteExpense('${e.id}')">Elimina</button></div></div>`).join('')}</div>`:`<div class="card empty">Nessuna spesa inserita.</div>`}`}
function duesView(){const rows=[...data.dueDates].sort((a,b)=>a.dueDate.localeCompare(b.dueDate));return `<h1>Scadenze</h1>${monthSelector()}${rows.length?`<div class="list">${rows.map(d=>{const paid=d.status==='paid';return `<div class="row"><div class="date">${dmy(d.dueDate)}</div><div><div class="title">${esc(d.title)}</div><div class="desc">${esc(cat(d.categoryId).name)} · ${paid?'Pagata':overdue(d)?'Scaduta':'Da pagare'} · ${dmyLong(d.dueDate)}</div></div><div class="value">${eur(d.amount)}<br><button class="secondary" style="padding:6px;margin-top:6px" onclick="${paid?`markDuePending('${d.id}')`:`markDuePaid('${d.id}')`}">${paid?'Ripristina':'Pagata'}</button></div></div>`}).join('')}</div>`:`<div class="card empty">Nessuna scadenza inserita.</div>`}`}
function budgetView(){const rows=catTotals(state.month);return `<h1>Budget</h1>${monthSelector()}<div class="card heroCard"><div class="kpiGrid"><div><span>Totale mese</span><strong>${eur(monthTotal(state.month))}</strong><small>Uscite + scadenze</small></div><div><span>Categorie</span><strong>${rows.length}</strong><small>Con movimenti</small></div></div><div class="chartWrap"><div class="chartTitle"><span>Andamento uscite mensili</span><span>${state.month.slice(0,4)}</span></div>${annualChartSvg()}</div></div>${rows.length?`<div class="list">${rows.map(r=>`<div class="row"><div class="roundIcon blue">€</div><div><div class="title">${esc(r.name)}</div><div class="desc">${monthLabel()}</div></div><div class="value">${eur(r.amount)}</div></div>`).join('')}</div>`:`<div class="card empty">Nessun dato per il mese.</div>`}`}
function settingsView(){return `<h1>Impostazioni</h1><div class="card"><div class="form"><div class="field"><label>Data avvio operativo</label><input readonly value="1 luglio 2026"></div><div class="field"><label>Notifiche</label><input readonly value="Web app + email nella prossima fase"></div><div class="themeChoice"><button class="${state.theme==='light'?'active':''}" onclick="toggleTheme()"><b>Tema chiaro/scuro</b><span>Stessa gestione stile TOTIME.</span></button></div><div class="actions"><button class="primary" onclick="seedDemo()">Carica dati demo</button><button class="secondary danger" onclick="clearData()">Cancella dati locali</button></div></div></div>`}
function markDuePaid(id){const d=data.dueDates.find(x=>x.id===id);if(d){d.status='paid';d.paidDate=todayISO;saveData();render()}}
function markDuePending(id){const d=data.dueDates.find(x=>x.id===id);if(d){d.status='pending';delete d.paidDate;saveData();render()}}
function deleteExpense(id){data.expenses=data.expenses.filter(e=>e.id!==id);data.dueDates=data.dueDates.filter(d=>d.sourceExpenseId!==id);saveData();render()}
function monthTotal(m){return data.expenses.filter(e=>isMonth(e.date,m)).reduce((s,e)=>s+Number(e.amount||0),0)+data.dueDates.filter(d=>isMonth(d.dueDate,m)).reduce((s,d)=>s+Number(d.amount||0),0)}
function catTotals(m){const map={};const add=(id,a)=>{const c=cat(id);map[id]??={name:c.name,amount:0};map[id].amount+=Number(a||0)};data.expenses.filter(e=>isMonth(e.date,m)).forEach(e=>add(e.categoryId,e.amount));data.dueDates.filter(d=>isMonth(d.dueDate,m)).forEach(d=>add(d.categoryId,d.amount));return Object.values(map).sort((a,b)=>b.amount-a.amount)}
function seedDemo(){data=defaultData();data.expenses=[{id:uid('exp'),title:'Spesa supermercato media',amount:180,date:'2026-07-06',categoryId:'alimentari',expenseType:'average_estimate',frequency:'weekly'},{id:uid('exp'),title:'Carburante',amount:90,date:'2026-07-08',categoryId:'auto',expenseType:'variable_recurring',frequency:'weekly'}];data.dueDates=[{id:uid('due'),title:'Mutuo casa',amount:850,dueDate:'2026-07-05',categoryId:'mutuo',status:'pending'},{id:uid('due'),title:'Assicurazione auto',amount:620,dueDate:'2026-07-15',categoryId:'assicurazioni',status:'pending'},{id:uid('due'),title:'TARI',amount:450,dueDate:'2026-11-30',categoryId:'tasse',status:'pending'}];saveData();state.view='home';setMsg('Dati demo caricati.')}
function clearData(){if(confirm('Cancellare i dati locali di Nest Egg?')){localStorage.removeItem(STORAGE_KEY);data=defaultData();render()}}
